FROM postgres:15

ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.3.2+dfsg-1.pgdg110+1

RUN apt-get update \
      && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
      && apt-get install -y --no-install-recommends \
      	   postgresql-15-ogr-fdw \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \
           make gcc g++ wget \
           postgresql-server-dev-$PG_MAJOR \
           libcurl4-openssl-dev \
	   postgresql-plpython3-15 \
	   postgresql-15-cron \
	   python3-pip \
      && rm -rf /var/lib/apt/lists/* \
      && pip install pyodk

#RUN localedef -i fr_FR -c -f UTF-8 -A /usr/share/locale/locale.alias fr_FR.UTF-8
#ENV LANG fr_FR.utf8

COPY ./.pyodk_config.toml /var/lib/postgresql/.pyodk_config.toml
COPY ./pl-pyODK.sql /var/lib/postgresql/pl-pyODK.sql

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh
COPY ./install_pl-pyODK.sh /docker-entrypoint-initdb.d/11_install_plpyodk.sh
COPY ./update-postgis.sh /usr/local/bin
